# (Mainly) For non-kubernetes users.
# Define the parameters below.

# Debug flag
test: True

# This must be unique.
# It can be overwritten with the environment variable "DRUCKER_APPLICATION_NAME".
app.name: drucker-sample

# It can be overwritten with the environment variable "DRUCKER_SERVICE_PORT".
app.port: 5000

# This must be unique.
# It can be overwritten with the environment variable "DRUCKER_SERVICE_NAME".
app.service.name: dev-001

# This must be one of [development/beta/staging/sandbox/production].
# It can be overwritten with the environment variable "DRUCKER_SERVICE_LEVEL".
app.service.level: development

# ML model
# Put your model file under "{app.modeldir}/{app.name}/{app.modelfile}".
# If you use Drucker-dashboard, {app.modelfile} is set automatically.
# If you setup MySQL server, {app.modelfile} is set automatically.
#   Model directory:  DRUCKER_SERVICE_MODEL_DIR > app.modeldir
#   Model filepath:   DB entry > DRUCKER_SERVICE_MODEL_FILE > app.modelfile
app.modeldir: ./model
app.modelfile: default.model

# DB
# "use.db" must be one of [sqlite(default)/mysql].
# If you use Drucker-dashboard, these values are set automatically.
#   DB type: DRUCKER_DB_MODE > use.db
#   MySQL host: DRUCKER_DB_MYSQL_HOST > db.mysql.host
#   MySQL port: DRUCKER_DB_MYSQL_PORT > db.mysql.port
#   MySQL DB name: DRUCKER_DB_MYSQL_DBNAME > db.mysql.dbname
#   MySQL user: DRUCKER_DB_MYSQL_USER > db.mysql.user
#   MySQL password: DRUCKER_DB_MYSQL_PASSWORD > db.mysql.password
use.db: sqlite
db.mysql.host: localhost
db.mysql.port: 3306
db.mysql.dbname: assignment
db.mysql.user: user
db.mysql.password: pass
